version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: dikshadhasmana/mongo:6.0
    container_name: webinar_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: webinar_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - webinar_network

  # Redis for caching and pub/sub
  redis:
    image: dikshadhasmana/redis:7.0-alpine
    container_name: webinar_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - webinar_network

  # Node.js Backend Application
  backend:
    image: dikshadhasmana/webinar-hosting-platform-backend:latest
    container_name: webinar_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/webinar_db?authSource=admin
      - REDIS_URL=redis://:redis123@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=https://webinar-hosting-platform-frontend.vercel.app
    depends_on:
      - mongodb
      - redis
    volumes:
      - recordings_data:/app/recordings
    networks:
      - webinar_network

volumes:
  mongodb_data:
  redis_data:
  recordings_data:

networks:
  webinar_network:
    driver: bridge